### ISSUE TITLE
Привет из QuikSharp

### ISSUE THREAD

**Issue by Agremond** [Pr0phet1c/QuikSharp---new#1]
Привет. К сожалению не нашел ваши контакты в профиле, поэтому пишут тут.
Давно знаком с проектом QuikSharp, спасибо за то что развиваете его.  Мне он очень помог для написания парочки приборов для работы с облигациями и фьючерсами. А сейчас пишу для себя опционный аналитический софт. Вот еще встал вопрос о написании торгового движка, который будет собирать опционные конструкции. Задача движка состоит в том, чтобы котировать инструменты, которые я формирую из основного кода программы. Чтобы покупал, продавал заданный объем по указанным мной инструментам, по нескольким одновременно. У меня есть кое какие старые наброски, но надо еще его отладить, а распылять силы не хочется. Так как движок вещь универсальная, то я подумал может быть у вас есть? Мой email: mailboxgmn@gmail.com

**Comment by Pr0phet1c** [comment]
К сожалению, не смогу понять чего именно Вы хотите.
Во-первых: у меня нет чего-то универсального, для использования другими людьми. Все что я пишу - делается исключительно под мои нужды, и по сути входит в единую инфраструктуру, из которой нельзя выдернуть кусок и передать на сторону. Оно просто не будет работать.
Во-вторых: Я не понимаю, какой смысл Вы вкладываете в понятие "торговый движок", и что значит фраза "...инструменты, которые я формирую..."
В-третьих: я не торгую опционами, но могу сказать, что софт для торговли опционами - это совершенно отдельная тема где нет никаких универсальных решений. Такие продукты не просто так существуют как самостоятельные программные продукты.

**Comment by Agremond** [comment]
Привет.
1. ок. понятно
2. "торговый движок" - класс или модуль с интерфейсами отправки ордеров с отслеживанием их статуса, в которым реализована низкая биржевая логика(отправка транзакций, отслеживание их выполнения, отмены, переноса через ночь и т.д.)
3. Все верно, опционный мир в РФ это куча разных велосипедов и парочка платных решений со своими плюсами/минусами. Я пишу свой велосипед, с функционалом которого нет в доступных решениях.
спасибо за коммент :)
